version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29-node
    steps:
      - checkout
      - run:
          name: Run Tests and linter
          command: ./gradlew lint test
